apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Values.label.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.label.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.label.name }}
      annotations:
        # Helm will not trigger a rollout if the deployment definition has not changed
        # In order to trigger a rollout when the config/secrets have changed, we include the checksums as an annotation
        configChecksum: {{ include (print $.Chart.Name "/templates/config-map.yaml") . | sha256sum }}
        secretChecksum: {{ include (print $.Chart.Name "/templates/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config-map
            - secretRef:
                name: {{ .Release.Name }}-secret