version: '3.4'

services:
  guestbook.api:
    image: ${DOCKER_REGISTRY-}guestbook
    build:
      context: .
      dockerfile: Guestbook.Api/Dockerfile

networks:
  default:
    external:
      name: guestbook-net