# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

resources:
- repo: self

variables:
  dockerfilePath: '$(Build.SourcesDirectory)/Guestbook.Api/Dockerfile'
  dockerRegistryServiceConnection: Guestbook Container Registry
  repository: guestbook-api # The image name will be repository:tag
  tag: '$(Build.Number)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        dockerfile: '$(dockerfilePath)'
        buildContext: '$(Build.SourcesDirectory)'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(repository)'
        tags: |
          $(tag)
