# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerfilePath: '$(Build.SourcesDirectory)/Guestbook.Api/Dockerfile'
  dockerRegistryServiceConnection: Guestbook Container Registry

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        dockerfile: '$(dockerfilePath)'
        buildContext: '$(Build.SourcesDirectory)'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: |
          $(tag)
