label:
  name: guestbook-api

container:
  name: guestbook-api
  pullPolicy: IfNotPresent
  image: globoticketclusteracr.azurecr.io/guestbook
  tag: 1
  port: 80

deployment:
  replicas: 1

service:
  port: 80
  type: ClusterIP

ingress:
  path: guestbook # App will be available at <cluster_ip>/<path>

config:
  storageProvider: InMemory
  guestbookCapacity: 3

secrets:
  storageConnectionString: SECRET